from fastapi import APIRouter, HTTPException, Depends
from models import Rule, RuleCreate, RuleType
from rule_engine import evaluate_rules, get_rule_summary
from supabase_client import get_current_user
from news_service import get_latest_news
from ai_service import evaluate_macro_ai_rules
import store
import uuid

router = APIRouter(prefix="/api/rules", tags=["rules"])


@router.get("/", response_model=list[Rule])
def get_rules(user_id: str = Depends(get_current_user)):
    return store.get_rules(user_id)


@router.post("/", response_model=Rule)
def create_rule(rule_data: RuleCreate, user_id: str = Depends(get_current_user)):
    # Build a preliminary schema with a valid temporary UUID bypass (store.py strips it and Supabase returns the true UUID)
    rule = Rule(
        id=str(uuid.uuid4()),
        name=rule_data.name,
        rule_type=rule_data.rule_type,
        threshold=rule_data.threshold,
        description=rule_data.description,
        target=rule_data.target,
        active=True,
    )
    saved_rule = store.add_rule(user_id, rule)
    return saved_rule

@router.put("/{rule_id}", response_model=Rule)
def edit_rule(rule_id: str, rule_data: RuleCreate, user_id: str = Depends(get_current_user)):
    # We construct a rule object, but preserve the existing UUID
    rule = Rule(
        id=rule_id,
        name=rule_data.name,
        rule_type=rule_data.rule_type,
        threshold=rule_data.threshold,
        description=rule_data.description,
        target=rule_data.target,
        active=True
    )
    # store.update_rules expects a list
    store.update_rules(user_id, [rule])
    return rule


@router.delete("/{rule_id}")
def delete_rule(rule_id: str, user_id: str = Depends(get_current_user)):
    deleted = store.delete_rule(user_id, rule_id)
    if not deleted:
        raise HTTPException(status_code=404, detail="Rule not found")
    return {"deleted": rule_id}


@router.post("/evaluate")
def evaluate_all_rules(user_id: str = Depends(get_current_user)):
    portfolio = store.get_portfolio(user_id)
    rules = store.get_rules(user_id)
    updated = evaluate_rules(portfolio, rules)
    store.update_rules(user_id, updated)
    triggered = [r for r in updated if r.triggered]
    alerts = [r.trigger_message for r in triggered if r.trigger_message]

    # Dynamically inject AI Macro Assessment
    try:
        news = get_latest_news(max_articles=5)
        ai_alert_msg = evaluate_macro_ai_rules(portfolio, news)
        if ai_alert_msg:
            ai_rule = Rule(
                id=str(uuid.uuid4())[:8],
                name="🤖 AI Macro Alert",
                rule_type=RuleType.CUSTOM_AI,
                threshold=0.0,
                description="Dynamically generated by analyzing global news against your portfolio.",
                active=True,
                triggered=True,
                trigger_message=ai_alert_msg
            )
            updated.insert(0, ai_rule) # Show at the top
            alerts.append(ai_alert_msg)
    except Exception as e:
        print(f"Error during AI evaluation: {e}")

    return {
        "rules": updated,
        "summary": get_rule_summary(updated),
        "alerts": alerts,
    }


@router.get("/types")
def get_rule_types(user_id: str = Depends(get_current_user)):
    return [
        {"value": "sector_cap",         "label": "Sector Concentration Cap",  "example": "Alert if any sector > X%"},
        {"value": "max_allocation",     "label": "Max Single Stock Allocation","example": "Alert if any stock > X%"},
        {"value": "stop_loss",          "label": "Stop-Loss Protection",       "example": "Alert if stock down > X%"},
        {"value": "volatility_trigger", "label": "Volatility Trigger",        "example": "Alert if portfolio vol > X%"},
        {"value": "crash_shift",        "label": "Crash Shift Signal",         "example": "Suggest bonds if market stress"},
        {"value": "auto_rebalance",     "label": "Auto-Rebalance Trigger",    "example": "Alert if asset drifts > X%"},
        {"value": "custom_ai",          "label": "Custom AI Rule",            "example": "Alert if Tech > 40% and MSFT drops"},
    ]
